name:                ghc-rules 
version:             0.1.0.0
github:              "faustind/ghc-rules"
license:             BSD3
author:              "Faustin Date"
maintainer:          "datefaustin@gmail.com"
copyright:           "2021 Faustin Date"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitHub at <https://github.com/faustind/ghc-rules#readme>

dependencies:
- base >= 4.7 && < 5
- ghc-paths
- ghc-lib
- filepath
- unix
- optparse-applicative

library:
  source-dirs: src

executables:
  ghc-rules:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ghc-rules
